---
- name: Create EC2 instances for ansible node (control nodes)
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[control_type].size }}"
    image: "{{ ansible_control_node_ami.image_id }}"
    region: "{{ ec2_region }}"
    count_tag:
      Workshop_ansible: "{{ ec2_name_prefix }}-ansible-aap-control{{ sequence }}"
    instance_tags:
      Workshop_ansible: "{{ ec2_name_prefix }}-ansible-aap-control{{ sequence }}"
      Workshop: "{{ ec2_name_prefix }}"
      AWS_USERNAME: "{{ aws_user }}"
      owner: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      username: "{{ ec2_info[control_type].username }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[control_type].disk_space }}"
        delete_on_termination: true
  register: control_output

- debug:
    msg: control_output

- name: Ensure tags are present
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-aap-control{{ sequence }}-node"
      Index: "{{ item[0] }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ control_output.instances }}"
  when: control_output.instance_ids is not none
